### ISSUE TITLE
When in watch mode emits on any dependency change.

### ISSUE THREAD

**Issue by subhaze** [hxlniada/webpack-concat-plugin#4]
Currently each time webpack runs due to a dependency change this plug-in reemits files even if the files it cares about haven't changed. It would be ideal to only emit on the first run, then only emit if a file passed into the plug-in changes.

I've worked out the bits to do this, save for cleaning somethings up. Would you be interested in a PR for this?

**Comment by hxlniada** [comment]
Yes，feel free to push a pr.🙂

**Comment by vhmth** [comment]
@subhaze I take it this has fallen off. I'd be really interested in this since concatting the 2 vendor bundles we're using adds 14 seconds to our rebuild times. I've had to result to using gulp/gulp watch for dev and then `webpack-concat-plugin` for prod so I can get the hash on the file (for CDN purposes).

**Comment by subhaze** [comment]
Unless something has changed this should be working. I had to do some modifications that were pretty opinionated so I'm not on the main release of this but a modified one. However, I've not changed any of the watching code that this ticket relates to that I'm aware of.

**Comment by vhmth** [comment]
Oh wow I see now that the PR got merged! In that case, I'll definitely take a deeper look to see why the concat plugin is taking up those extra 14s on reloads! Probably something in the way I have my config setup.
